### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by sun-geo** [matkoniecz/illegal-use-of-OpenStreetMap#7]
README.md

last line <del>undestandable</del> => "understandable"

https://github.com/matkoniecz/illegal-use-of-OpenStreetMap/blob/master/MAPS.ME/MAPS.ME.md#mapsme

"And <del>Moovit</del> _Mapsme_ still failed to follow"

By the way, do you know any android navigation-app which uses osm-data and does show the osm-attribution as expected? (as a positive example...)

There are maybe more candidates: osmand / magic earth?

**Comment by matkoniecz** [comment]
> By the way, do you know any android navigation-app which uses osm-data and does show the osm-attribution as expected? (as a positive example...)

Well, StreetComplete editor has an attribution for its OSM powered map.

What triggered creation of this project is that I was planning a feature thanking user for editing and giving a specific examples of how OSM data is used. I was looking for candidates and failed to find a single useful recommendable application for Android that would attribute OSM properly (except StreetComplete itself).

--------

OsmAnd at least added "powered by OpenStreetMap data" at the startup screen, within 9 days from requesting it, with release landing some time later. See https://github.com/osmandapp/Osmand/issues/7219#issuecomment-512710790 - it is deployed in a current version, and is visible during secondary part of the loading screen. Note that it is visible for longer on phones based on a worse hardware.

It is likely not a sufficient attribution. I see nothing clearly visible within app after it loads, but I decided to focus on MAPS.ME and Moovit for now due to their behavior.

To compare - I opened an equivalent MAPS.ME issue on the same day in July 2019, for now without any real effect 150 days later. See https://github.com/mapsme/omim/issues/11203

**Comment by matkoniecz** [comment]
Typos fixed, thanks for reporting!

**Comment by sun-geo** [comment]
> Well, the StreetComplete editor has a clear attribution

Thanks, thats true, sorry i forgot this app, because i'm using mainly desktop pc editors.

> What triggered...

Very interesting, and good idea! :-)

> OsmAnd at least...

Thats true, better than nothing. Maybe one day they can manage the same nice display as StreetComplete it does it.

Thanks for instant typo-fixing.

By the way, in general, i have an amateur feeling, that all these software developers are not willing to omit the requested attribution by intention, i think there are maybe just mostly too strong technical hurdle(*) to implement an attribution-display-function.

I'm not a developer, but maybe it could be helpfull, if there are more easier (open source) templates/plugin/modules of attribution available, which could be relatively easy (as black box) integrated in several different osm-map-displaying-projects. 
The creation of such templates/plugin could maybe done by the osm-community itself or even by any additional support of the osm-foundation.

I think this would help both sides.

(*) e.g. here is a help request from a develorer:
https://github.com/jpatokal/openflights/issues/916

**Comment by matkoniecz** [comment]
> By the way, in general, i have an amateur feeling, that all these software developers are not willing to omit the requested attribution by intention, i think there are maybe just mostly too strong technical hurdle(*) to implement an attribution-display-function.

Note that MAPS.ME implemented attribution (bottom right corner, see [this screenshot](https://raw.githubusercontent.com/matkoniecz/illegal-use-of-OpenStreetMap/master/MAPS.ME/MAPS.ME_application_missing_attribution_misleading_one_present_screenshot_2019-09-09-17-44-05.png) ). But they just decided to describe "MAPS.ME" as authors.

And compared to other things required in developing application displaying attribution is not so hard.

**Comment by sun-geo** [comment]
I agree - oh yes, maps.me only needs to change this string...

So for bigger projects it should be doable, for small (maybe one or two persons) projects, which run in their spare time, the community could give support...
